#!/bin/bash -xe

cd 

curl -L https://github.com/opencv/opencv/archive/4.0.0.zip  --output opencv.zip
curl -L https://github.com/opencv/opencv_contrib/archive/4.0.0.zip --output opencv_contrib.zip

unzip opencv.zip 
unzip opencv_contrib.zip

mv opencv-4.0.0 opencv
mv opencv_contrib-4.0.0 opencv_contrib

